accounts/urls.py
from django.urls import path

from accounts.views import(
    registrer_view,
    login_view,
    logout_view,
    change_password_view
)


urlpatterns = [
    path("register/", registrer_view, name="register"),
    path("login/", login_view, name="login"),
    path("logout/", logout_view, name="logout"),
    path("change-password/", change_password_view, name="change_password"),
]

app_name = "accounts"

journeynotes/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("journeys.urls")),
    path("", include("accounts.urls")),
]

journeys/urls.py
from django.urls import path

from journeys.views import(
    journey_list_view,
    journey_detail_view,
    journey_create_view,
    journey_update_view,
    journey_delete_view,
    add_comment_view,
    add_to_favorite_view,
)

urlpatterns = [
    path("journeys-list/", journey_list_view, name="journeys_list"),
    path("journeys/<int:pk>/", journey_detail_view, name="journey_detail"),
    path("journeys/create/", journey_create_view, name="journey_create"),
    path("journeys/<int:pk>/update/", journey_update_view, name="journey_update"),
    path("journeys/<int:pk>/delete/", journey_delete_view, name="journey_delete"),
    path("journeys/<int:pk>/add-comment", add_comment_view, name="add_comment"),
    path("journeys/<int:pk>/add-to_favorite", add_to_favorite_view, name="add_to_favorite"),
]

app_name = "journeys"

templates/includes/header.html
<header>
  <nav>
    {% if user.is_authenticated %}
      <p>Welcome, {{ user.username }}!</p>
      <a href="{% url "journeys:journey_create" %}">Create Journey</a> |
      <a href="{% url "accounts:logout" %}">Logout</a>
    {% else %}
      <a href="{% url "accounts:login" %}">Login</a> |
      <a href="{% url "accounts:register" %}">Register</a>
    {% endif %}
  </nav>
  <hr>
</header>