accounts/urls.py
from django.urls import path

from accounts.views import(
    registrer_view,
    login_view,
    logout_view,
    change_password_view
)


urlpatterns = [
    path("register/", registrer_view, name="register"),
    path("login/", login_view, name="login"),
    path("logout/", logout_view, name="logout"),
    path("change-password/", change_password_view, name="change_password"),
]

app_name = "accounts"

journeynotes/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("journeys.urls")),
    path("", include("accounts.urls")),
]

journeys/urls.py
from django.urls import path

from journeys.views import(
    journey_list_view,
    journey_detail_view,
    journey_create_view,
    journey_update_view,
    journey_delete_view,
    add_comment_view,
    add_to_favorite_view,
)

urlpatterns = [
    path("journeys-list/", journey_list_view, name="journeys_list"),
    path("journeys/<int:pk>/", journey_detail_view, name="journey_detail"),
    path("journeys/create/", journey_create_view, name="journey_create"),
    path("journeys/<int:pk>/update/", journey_update_view, name="journey_update"),
    path("journeys/<int:pk>/delete/", journey_delete_view, name="journey_delete"),
    path("journeys/<int:pk>/add-comment", add_comment_view, name="add_comment"),
    path("journeys/<int:pk>/add-to_favorite", add_to_favorite_view, name="add_to_favorite"),
]

app_name = "journeys"

journeys/models.py
from django.db import models
from django.conf import settings


class Route(models.Model):
    title = models.CharField(max_length=63, blank=False, null=False)
    content = models.TextField(blank=True, null=True)
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="routes"
    )
    path = models.JSONField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ["-updated_at"]


class Comment(models.Model):
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="comments"
    )
    route = models.ForeignKey(
        Route,
        on_delete=models.CASCADE,
        related_name="comments"
    )
    content = models.TextField(blank=False, null=False)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.content[:30]

journeys/forms.py
from django import forms

from journeys.models import Route, Comment

class JourneyForm(forms.ModelForm):
    class Meta:
        model = Route
        fields = ["title", "content"]


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["content"]


class RouteTitleSearchForm(forms.Form):
    title = forms.CharField(
        max_length=63,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={
                "placeholder": "Search by title"
            }
        )
    )

journeys/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpRequest, HttpResponse
from django.db.models import Count, Prefetch
from django.contrib.auth.decorators import login_required

from journeys.models import Route, Comment
from journeys.forms import JourneyForm, CommentForm, RouteTitleSearchForm
from accounts.models import Traveler


def journey_list_view(request: HttpRequest) -> HttpResponse:    
    journeys_list = (
        Route.objects
        .select_related("author")
        .annotate(comment_count=Count("comments"))
        .order_by("-updated_at")
    )

    search_form = RouteTitleSearchForm(request.GET)
    if search_form.is_valid():
        title = search_form.cleaned_data["title"]
        journeys_list = journeys_list.filter(title__icontains=title)
    else:
        title = ""
    search_form = RouteTitleSearchForm(initial={"title": title})
    context = {
        "journeys_list": journeys_list,
        "search_form": search_form,
    }
    return render(request, "journeys/journeys-list.html", context=context)


def journey_detail_view(request: HttpRequest, pk: int) -> HttpResponse:
    journey_detail = (
        Route.objects
        .select_related("author")
        .annotate(comment_count=Count("comments"))
        .prefetch_related(
            Prefetch("comments", queryset=Comment.objects.select_related("author"))
        )
        .get(pk=pk)
    )
    favorites_count = journey_detail.liked_by.count()
    is_favorite = False
    if request.user.is_authenticated:
        is_favorite = journey_detail.liked_by.filter(pk=request.user.pk).exists()
    form = CommentForm()
    context = {
        "journey_detail": journey_detail,
        "form": form,
        "favorites_count": favorites_count,
        "is_favorite": is_favorite
    }
    return render(request, "journeys/journey-detail.html", context=context)


@login_required
def add_to_favorite_view(request: HttpRequest, pk: int) -> HttpResponse:
    if request.method == "POST":
        route = Route.objects.get(pk=pk)
        if route.author != request.user:
            author = Traveler.objects.get(pk=request.user.pk)
            if not author.favorite_routs.filter(pk=route.pk).exists():
                author.favorite_routs.add(route)
                return redirect("journeys:journey_detail", pk=pk)
            else:
                author.favorite_routs.remove(route)
                return redirect("journeys:journey_detail", pk=pk)
                


@login_required
def journey_create_view(request: HttpRequest) -> HttpResponse:
    if request.method == "POST":
        form = JourneyForm(request.POST)
        if form.is_valid():
            journey = form.save(commit=False)
            journey.author = request.user
            journey.save() 
            return redirect("journeys:journeys_list")
    else:
        form = JourneyForm()
    return render(request, "journeys/journey-create.html", {"form": form})


@login_required
def journey_update_view(request: HttpRequest, pk: int) -> HttpResponse:
    journey = get_object_or_404(Route, pk=pk)
    if journey.author != request.user:
        return redirect("journeys:journeys_list")

    if request.method == "POST":
        form = JourneyForm(request.POST, instance=journey)
        if form.is_valid():
            form.save()
            return redirect("journeys:journeys_list")
    else:
        form = JourneyForm(instance=journey)

    return render(request, "journeys/journey-update.html", {"form": form})


@login_required
def journey_delete_view(request: HttpRequest, pk: int) -> HttpResponse:
    if request.method == "POST":
        obj = get_object_or_404(Route, pk=pk)
        if obj.author == request.user:
            obj.delete()
        return redirect("journeys:journeys_list")
    else:
        return render(request, "journeys/journey-delete.html")


@login_required
def add_comment_view(request: HttpRequest, pk: int) -> HttpResponse:
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.route = Route.objects.get(pk=pk)
            comment.save()
            return redirect("journeys:journey_detail", pk=pk)
    else:
        return redirect("journeys:journey_detail", pk=pk)


templates/journeys/journey-create.html
{% extends "base.html" %}
{% block title %}
  <title>Create new Journey</title>
{% endblock title %}

{% block content %}
  <h1>Tell about your journey:</h1>
  <a href="{% url "journeys:journeys_list" %}">Go back</a>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form.non_field_errors }}
    {{ form.as_p}}
    <button type="submit">Submit</button>
  </form>
{% endblock content %}

templates/journeys/journey-delete.html
{% extends "base.html" %}
{% block title %}
  <title>Delete Journey</title>
{% endblock title %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete your journey?</p>
    <a href="{% url "journeys:journeys_list" %}">Go back</a>
    <button type="submit">Delete journey!</button>
  </form>
{% endblock content %}

templates/journeys/journey-detail.html
{% extends "base.html" %}
{% block content %}
  <h1>{{ journey_detail.title }}</h1>
  <h3>Posted by: {{ journey_detail.author.username }} at: {{ journey_detail.updated_at }}</h3>
  {% if user == journey_detail.author %}
    <a href="{% url "journeys:journey_update" pk=journey_detail.pk %}">Edit journey</a>
    <a href="{% url "journeys:journey_delete" pk=journey_detail.pk %}">Delete journey</a>
  {% endif %}
  <a href="{% url "journeys:journeys_list" %}">Go back</a>
  <p>{{ journey_detail.content }}</p>
  <br>
  {% if user.is_authenticated and user != journey_detail.author %}
    <form action="{% url "journeys:add_to_favorite" pk=journey_detail.pk %}" method="post">
      {% csrf_token %}
      <button type="submit">
        {% if is_favorite %}remove from favorite 💚{% else %}add to favorite 🤍{% endif %}
      </button>
    </form>
  {% endif %}
  <br>
  <p>This rout was added to favorite: {{ favorites_count }} times.
  <hr>
  <br>
  {% if journey_detail.comment_count > 0 %}
    <h2>This route has: {{ journey_detail.comment_count }} comments</h2>
    {% for comment in journey_detail.comments.all %}
      <h3>{{ comment.author.username }} at: {{ comment.created_at }}</h3>
      <p>{{ comment.content }}</p>
    {% endfor %}
  {% else %}
    <h2>No comments yet :(</h2>
  {% endif %}
  <hr>
  <h2>Add a comment:</h2>

  {% if form.errors %}
    <ul>
      {% for field in form %}
        {% for error in field.errors %}
          <li>{{ error }}</li>
        {% endfor %}
      {% endfor %}
      {% for error in form.non_field_errors %}
        <li>{{ error }}</li>
      {% endfor %}
    </ul>
  {% endif %}

  <form action="{% url "journeys:add_comment" pk=journey_detail.pk %}" method="post" novalidate>
    {% csrf_token %}
    {{ form.as_p }}
    {% if user.is_authenticated %}
      <button type="submit">Add comment</button>
    {% else %}
      <a href="{% url "accounts:register" %}">Register to leave a comment</a>
    {% endif %}
  </form>
{% endblock content %}

templates/journeys/journey-update.html
{% extends "base.html" %}
{% block title %}
  <title>Update your journey</title>
{% endblock title %}

{% block content %}
  <h1>Edit your journey</h1>
    <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form.non_field_errors }}
    {{ form.as_p}}
    <a href="{% url "journeys:journeys_list" %}">Go back</a>
    <button type="submit">Submit</button>
  </form>
{% endblock content %}

templates/journeys/journeys-list.html
{% extends "base.html" %}
{% block content %}
  <form action="" method="get">
      {{ search_form }}
      <button type="submit">Search 🔎</button>
  </form>
  {% if journeys_list %}
    <h1>All travels:</h1>
    {% for journey in journeys_list %}
      <h2><a href="{% url "journeys:journey_detail" pk=journey.pk %}">{{ journey.title }}</a></h2>
      <h3>Posted by: {{ journey.author.username }} at: {{ journey.updated_at }}</h3>
      <p>{{ journey.content }}</p>
      <hr>
    {% endfor %}
  {% else %}
    <h1>No journeys available yet :(</h1>
  {% endif %}
{% endblock content %}